name: slabgcn
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ase=3.22.1=pyhd8ed1ab_1
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - black=24.1.1=py38h578d9bd_0
  - blinker=1.7.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py38h17151c0_1
  - ca-certificates=2024.2.2=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.1=py38h17151c0_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - flask=3.0.2=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - greenlet=3.0.3=py38h17151c0_0
  - icu=67.1=he1b5a44_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - ipykernel=6.14.0=py38h7f3c49e_0
  - ipython=8.4.0=py38h578d9bd_0
  - isort=5.13.2=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py38h578d9bd_0
  - kiwisolver=1.4.5=py38h7f3f72f_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=20_linux64_openblas
  - libcblas=3.9.0=20_linux64_openblas
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libgomp=13.2.0=h807b86a_5
  - liblapack=3.9.0=20_linux64_openblas
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.42=h2797004_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.44.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libzlib=1.2.13=hd590300_5
  - markupsafe=2.1.5=py38h01eb140_0
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py38h5d868c9_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mendeleev=0.15.0=pyhc1e730c_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.4=h59595ed_2
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.24.4=py38h59b608b_0
  - openssl=1.1.1w=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.0.3=py38h01efb38_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.12.1=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pooch=1.8.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py38h01eb140_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyfiglet=0.8.post1=py_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.5=h1103e12_9_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.4=pyhd8ed1ab_0
  - python_abi=3.8=4_cp38
  - pytz=2024.1=pyhd8ed1ab_0
  - pyzmq=25.1.2=py38h34c975a_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - scikit-learn=1.3.2=py38ha25d942_2
  - scipy=1.10.1=py38h59b608b_3
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=2.0.25=py38h01eb140_0
  - sqlite=3.44.2=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py38h7f0c24c_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.3=py38h01eb140_1
  - traitlets=5.14.1=pyhd8ed1ab_0
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - urllib3=2.2.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - pip:
      - cmake==3.28.1
      - emmet-core==0.68.0
      - filelock==3.13.1
      - future==0.18.3
      - latexcodec==2.0.1
      - lit==17.0.6
      - monty==2023.9.25
      - mp-api==0.35.1
      - mpmath==1.3.0
      - msgpack==1.0.7
      - networkx==3.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - palettable==3.3.3
      - pillow==10.2.0
      - plotly==5.18.0
      - pybtex==0.24.0
      - pydantic==1.10.14
      - pymatgen==2023.8.10
      - pyyaml==6.0.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - spglib==2.3.0
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - torch==2.0.1
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2+pt20cu117
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tqdm==4.66.1
      - triton==2.0.0
      - uncertainties==3.1.7
